# ~/.config/starship.toml

# Global options (from `settings` block)
add_newline = true
command_timeout = 2000

# This is where the 'format' string goes, translated from `lib.concatStrings`
# Each item in the `lib.concatStrings` list becomes a segment in the string.
format = """\
[ ](#2361ad)\
$os\
$username\
[](fg:#2361ad bg:#3f75cd)\
$directory\
[](fg:#3f75cd bg:#20bd86)\
$git_branch\
$git_status\
[](fg:#20bd86 bg:#a3be8c)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:#a3be8c bg:#229ab3)\
$time\
[](fg:#229ab3)\
$line_break\
$character\
"""

# Module Definitions (from nested blocks like `os = { ... }`)

[os]
disabled = false
style = "bg:#2361ad fg:#ffffff"

[os.symbols]
NixOS = "" # Note: This symbol will only show if you're on NixOS. On Fedora, it'll likely be blank or default.
Fedora = ""

[username]
show_always = true
style_user = "bg:#2361ad fg:#ffffff"
style_root = "bg:#5e81ac fg:#ffffff"
format = "[ $user ]($style)" # Removed the extra `(bg:#5e81ac fg:base06)` as style already applies it.

[directory]
style = "bg:#3f75cd fg:#ffffff"
format = "[ $path ]($style)"
use_os_path_sep = true
truncate_to_repo = false
#truncation_length = 3
#truncation_symbol = "..."

[directory.substitutions]
Documents = "󰈙"
Downloads = ""
Music = "󰝚"
Pictures = ""

[git_branch]
symbol = ""
style = "bg:#20bd86"
# The format string was complex; let's simplify for direct TOML and common usage.
# If you want the nested brackets, you need to be careful with escaping.
# Assuming you want `( symbol branch )` and `( status ahead_behind )`
format = "[ ( $symbol$branch(:$remote_branch) )](fg:#0f0f0f bg:#20bd86)"


[git_status]
style = "bg:#20bd86"
format = "[ ( $all_status$ahead_behind )](fg:#0f0f0f bg:#20bd86)"

[nodejs]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:#ffffff bg:#a3be8c)"

[c]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:base06 bg:#a3be8c)"

[cpp]
disabled = false
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:base06 bg:#a3be8c)"

[rust]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:base06 bg:#a3be8c)"

[php]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:base06 bg:#a3be8c)"

[java]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:base06 bg:#a3be8c)"

[kotlin]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:base06 bg:#a3be8c)"

[haskell]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:base06 bg:#a3be8c)"

[python]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:base06 bg:#a3be8c)"

[time]
disabled = false
time_format = "%r"
style = "bg:a3be8c"
format = "[[  $time ](fg:#ffffff bg:#229ab3)]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[](bold fg:#18D661)"
error_symbol = "[](bold fg:#d62929)"
